# Generated by Django 2.2.10 on 2020-02-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('join_date', models.DateTimeField()),
                ('hidden', models.IntegerField()),
                ('STV', models.FloatField()),
                ('target', models.FloatField()),
                ('credit_card_level', models.CharField(max_length=1000)),
                ('is_lp', models.IntegerField()),
                ('aff_type', models.CharField(max_length=1000)),
                ('is_cancelled', models.IntegerField()),
                ('country_segment', models.CharField(max_length=1000)),
            ],
        ),
    ]
