# Generated by Django 2.2.10 on 2020-02-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20200216_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='aff_type',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='country_segment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='credit_card_level',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
