# Generated by Django 2.2.10 on 2020-02-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('join_date', models.DateTimeField()),
                ('hidden', models.IntegerField(null=True)),
                ('STV', models.FloatField()),
                ('target', models.FloatField()),
                ('credit_card_level', models.CharField(max_length=1000, null=True)),
                ('is_lp', models.IntegerField(null=True)),
                ('aff_type', models.CharField(max_length=1000, null=True)),
                ('is_cancelled', models.IntegerField(null=True)),
                ('country_segment', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('prediction', models.FloatField()),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='models.Feature')),
            ],
        ),
    ]
