# Generated by Django 3.0.3 on 2020-02-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_afftype_country_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='STV',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='target',
            field=models.FloatField(null=True),
        ),
    ]
